"""Alert rules: the built-in ones, and a check for user rule files.

Rules are plain Prometheus/vmalert rule files. The built-in file is regenerated by the
plugin; users add their own as ``<lab>/monitoring/alerts/*.yml`` (reloaded within seconds,
no restart). vmalert writes ``ALERTS`` back to the TSDB, so firing alerts can be queried and
graphed like any metric.
"""

from __future__ import annotations

import typing

import yaml

from . import catalog


def _rule(alert: str, expr: str, summary: str, severity: str = "critical", wait: str = "1m") -> dict:
    return {
        "alert": alert,
        "expr": expr,
        "for": wait,
        "labels": {"severity": severity},
        "annotations": {"summary": summary},
    }


BUILTIN = {
    "groups": [
        {
            "name": "netlab-intent",
            "interval": "15s",
            "rules": [
                _rule(
                    "NetlabBgpSessionDown",
                    "netlab_expected_bgp_session unless on(lab,node,peer,vrf) (netlab_bgp_session_up == 1)",
                    "{{ $labels.node }}: BGP session to {{ $labels.peer }} is not established",
                ),
                _rule(
                    "NetlabVxlanVniMissing",
                    "netlab_expected_vxlan_vni unless on(lab,node,vni) (netlab_vxlan_vni_up == 1)",
                    "{{ $labels.node }}: VXLAN VNI {{ $labels.vni }} is not up",
                ),
                _rule(
                    "NetlabOspfAdjacencyDown",
                    "netlab_expected_ospf_adjacency unless on(lab,node,peer_node,ifname)"
                    " (netlab_ospf_neighbor_up == 1)",
                    "{{ $labels.node }}: OSPF adjacency with {{ $labels.peer_node }} on {{ $labels.ifname }} is not up",
                ),
                _rule(
                    "NetlabIsisAdjacencyDown",
                    "netlab_expected_isis_adjacency unless on(lab,node,peer_node,ifname)"
                    " (netlab_isis_adjacency_up == 1)",
                    "{{ $labels.node }}: IS-IS adjacency with {{ $labels.peer_node }}"
                    " on {{ $labels.ifname }} is not up",
                ),
            ],
        },
        {
            "name": "netlab-health",
            "interval": "15s",
            "rules": [
                _rule("NetlabNodeDown", "netlab_node_up == 0", "{{ $labels.node }} is not running", wait="30s"),
                _rule(
                    "NetlabCollectorFailing",
                    "netlab_collector_up == 0",
                    "Collecting {{ $labels.node }} with {{ $labels.method }} fails: its monitoring data is stale",
                    severity="warning",
                ),
            ],
        },
    ]
}

EXAMPLE = """\
# Your own alert rules (Prometheus/vmalert format). Files here reload within ~10 seconds.
# Firing alerts: http://<host>:8880 (vmalert) and the ALERTS metric in Grafana.
# Metrics and labels: monitoring/METRICS.md. The lab and node labels are always present.
groups:
  - name: my-rules
    rules:
      # A recording rule: compute an expression once, query it by name.
      - record: netlab:node_memory_gib
        expr: netlab_node_memory_bytes / 2^30
      # An alert, for example: uncomment and adjust.
      # - alert: HighMemory
      #   expr: netlab:node_memory_gib > 1.5
      #   for: 2m
      #   labels: { severity: warning }
      #   annotations: { summary: "{{ $labels.node }} uses {{ $value | humanize }} GiB" }
"""


def builtin_yaml() -> str:
    header = "# Built-in rules, regenerated by the monitoring plugin. Add your own in ../alerts/\n"
    return header + yaml.safe_dump(BUILTIN, sort_keys=False, width=140)


def check(text: str) -> tuple[list[str], list[str]]:
    """Validate a rule file. Returns (errors, warnings); an error means vmalert would reject it."""
    try:
        doc = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        return [f"not valid YAML: {exc}"], []
    groups = doc.get("groups") if isinstance(doc, dict) else None
    if not isinstance(groups, list) or not groups:
        return ["needs a top-level 'groups' list"], []
    errors: list[str] = []
    warns: list[str] = []
    for g, group in enumerate(groups, 1):
        rules = group.get("rules") if isinstance(group, dict) else None
        if not isinstance(group, dict) or not group.get("name") or not isinstance(rules, list):
            errors.append(f"group {g}: needs 'name' and a 'rules' list")
            continue
        for r, rule in enumerate(rules, 1):
            where = f"{group['name']} rule {r}"
            if not isinstance(rule, dict) or not (rule.get("alert") or rule.get("record")):
                errors.append(f"{where}: needs 'alert' (name) or 'record' (name)")
            elif not rule.get("expr"):
                errors.append(f"{where}: needs 'expr'")
            else:
                warns += [
                    f"{where}: unknown metric {m}" for m in catalog.unknown_metrics(typing.cast(str, rule["expr"]))
                ]
    return errors, warns
