"""The stack as containers: `docker run` scripts (placement: tool) and netlab nodes (placement: node)."""

from __future__ import annotations

import json
import shlex

from . import logs, notify
from .endpoints import DEFAULT_PORTS, Endpoints, needs
from .grafana import USER_DASHBOARDS_MOUNT, grafana_env
from .plan import get


def tsdb_args(cfg: dict, listen_port: int, config_path: str, storage: str) -> list[str]:
    return [
        f"-storageDataPath={storage}",
        f"-retentionPeriod={cfg.get('retention') or '7d'}",
        f"-httpListenAddr=:{listen_port}",
        f"-promscrape.config={config_path}",
        "-search.latencyOffset=2s",  # show fresh samples right away (lab, not a WAN)
        "-promscrape.config.strictParse=false",
    ]


def vmalert_args(tsdb: str, listen_addr: str, alertmanager: str | None = None) -> list[str]:
    """vmalert evaluates the built-in and the user's rules against the TSDB and writes ALERTS back.

    With ``alertmanager`` (host:port) firing alerts are also sent there; without it they stay in
    vmalert and the ALERTS metric."""
    return [
        "-rule=/monitoring/rules/*.yml",
        "-rule=/monitoring/alerts/*.yml",
        f"-datasource.url=http://{tsdb}",
        f"-remoteWrite.url=http://{tsdb}",
        f"-httpListenAddr={listen_addr}",
        "-configCheckInterval=10s",
        "-evaluationInterval=15s",
        f"-notifier.url=http://{alertmanager}" if alertmanager else "-notifier.blackhole",
    ]


def alertmanager_args(listen_addr: str) -> list[str]:
    return [
        "--config.file=/monitoring/alertmanager/alertmanager.yml",
        f"--web.listen-address={listen_addr}",
        "--storage.path=/alertmanager",
        "--cluster.listen-address=",  # single instance: no gossip port
    ]


# Every container role the stack can have (a lab uses the ones it needs).
ROLES = ("collector", "tsdb", "vmalert", "alertmanager", "loki", "vector", "grafana", "gnmic", "snmp")

# ------------------------------------------------------------------ tool placement scripts


def _container(name: str, image: str, args: list[str], opts: list[str], lab: str, role: str) -> str:
    cmd = [
        "docker",
        "run",
        "-d",
        "--name",
        name,
        "--restart",
        "unless-stopped",
        "--network",
        "host",
        "--label",
        f"netlab.lab={lab}",
        "--label",
        f"netlab.monitoring={role}",
        *opts,
        image,
        *args,
    ]
    return " ".join(shlex.quote(c) if not c.startswith('"$') else c for c in cmd)


def port_check_code(listeners: list[tuple[str, int, str]]) -> str:
    """Python that exits 1, naming every port in ``listeners`` (component, port, tcp|udp) that is taken.

    The stack runs on the host network, so a port another program already holds makes that
    container fail to bind and restart forever while ``netlab up`` still says it started, and the UI
    then opens the other program. A port is tested by binding it, as the container would."""
    return (
        "import json, socket, sys\n"
        f"listeners = json.loads({json.dumps(json.dumps(listeners))})\n"
        "busy = []\n"
        "for name, port, proto in listeners:\n"
        "    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM if proto == 'udp' else socket.SOCK_STREAM)\n"
        "    try:\n"
        "        s.bind(('0.0.0.0', port))\n"
        "    except OSError:\n"
        "        busy.append((name, port))\n"
        "    finally:\n"
        "        s.close()\n"
        "for name, port in busy:\n"
        "    print(f'monitoring: port {port} ({name}) is already in use by another program; free it or set '\n"
        "          f'monitoring.ports.{name} in the topology', file=sys.stderr)\n"
        "sys.exit(1 if busy else 0)\n"
    )


def tool_scripts(plan: dict, cfg: dict, ep: Endpoints) -> dict[str, str]:
    lab = plan["lab"]
    images = cfg.get("images") or {}
    names = {role: f"{lab}_mon_{role}" for role in ROLES}
    use_logs, use_notify = logs.enabled(cfg), notify.enabled(cfg)
    uses_libvirt = any(n.get("provider") == "libvirt" for n in plan["nodes"].values())
    collector_port = ep.collector.rsplit(":", 1)[1]
    listeners = [
        ("collector", int(collector_port), "tcp"),
        ("tsdb", ep.tsdb_port, "tcp"),
        ("vmalert", ep.vmalert_port, "tcp"),
    ]
    if use_notify:
        listeners.append(("alertmanager", ep.alertmanager_port, "tcp"))
    if use_logs:
        listeners += [("loki", ep.loki_port, "tcp"), ("loki_grpc", ep.loki_grpc_port, "tcp")]
        listeners.append(("syslog", ep.syslog_port, "udp"))
    if needs(plan, "gnmi"):
        listeners.append(("gnmic", int(ep.gnmic.rsplit(":", 1)[1]), "tcp"))
    if needs(plan, "snmp"):
        listeners.append(("snmp", int(ep.snmp.rsplit(":", 1)[1]), "tcp"))
    if get(cfg, "grafana.enabled", True):
        listeners.append(("grafana", ep.grafana_port, "tcp"))
    lines = [
        "#!/bin/bash",
        "# Generated by the netlab monitoring plugin: start the monitoring stack (netlab up runs this)",
        "set -e",
        'cd "$(dirname "$0")/.."',
        f"docker rm -f {' '.join(names.values())} >/dev/null 2>&1 || true",
        "# Stop with a clear message if a port is taken (see port_check_code); skipped without python3.",
        "if command -v python3 >/dev/null 2>&1; then",
        "python3 - <<'NETLAB_PORT_CHECK' || exit 1",
        port_check_code(listeners).rstrip("\n"),
        "NETLAB_PORT_CHECK",
        "fi",
        "mkdir -p monitoring/data/tsdb monitoring/data/grafana monitoring/dashboards monitoring/alerts",
        "chmod 777 monitoring/data/grafana  # written by the Grafana container user",
        *(
            [
                "mkdir -p monitoring/data/loki monitoring/data/vector",
                "chmod 777 monitoring/data/loki monitoring/data/vector  # written by the containers' own users",
            ]
            if use_logs
            else []
        ),
        _container(
            names["collector"],
            images.get("collector", "python:3.13-alpine"),
            [
                "python3",
                "-m",
                "nlmon",
                "--plan",
                "/monitoring/plan.json",
                "--listen",
                f"127.0.0.1:{collector_port}",
                "--proc",
                "/proc",
                "--sys",
                "/host/sys",
            ],
            [
                "--pid",
                "host",
                "--cgroupns",
                "host",
                "--privileged",
                "-e",
                "PYTHONPATH=/monitoring/collector",
                "-v",
                "/sys:/host/sys:ro",
                "-v",
                "/var/run/docker.sock:/var/run/docker.sock:ro",
                *(["-v", "/run/libvirt:/run/libvirt:ro"] if uses_libvirt else []),
                "-v",
                '"$PWD/monitoring:/monitoring:ro"',
            ],
            lab,
            "collector",
        ),
        _container(
            names["tsdb"],
            images.get("tsdb", "victoriametrics/victoria-metrics"),
            tsdb_args(cfg, ep.tsdb_port, "/monitoring/tsdb/scrape.yml", "/storage"),
            ["-v", '"$PWD/monitoring:/monitoring:ro"', "-v", '"$PWD/monitoring/data/tsdb:/storage"'],
            lab,
            "tsdb",
        ),
        _container(
            names["vmalert"],
            images.get("vmalert", "victoriametrics/vmalert"),
            vmalert_args(ep.tsdb, f"127.0.0.1:{ep.vmalert_port}", ep.alertmanager if use_notify else None),
            ["-v", '"$PWD/monitoring:/monitoring:ro"'],
            lab,
            "vmalert",
        ),
    ]
    if use_notify:
        lines.append(
            _container(
                names["alertmanager"],
                images.get("alertmanager", "prom/alertmanager"),
                [*alertmanager_args(f"127.0.0.1:{ep.alertmanager_port}")],
                ["-v", '"$PWD/monitoring:/monitoring:ro"'],
                lab,
                "alertmanager",
            )
        )
    if use_logs:
        lines += [
            _container(
                names["loki"],
                images.get("loki", "grafana/loki"),
                ["-config.file=/monitoring/loki/loki.yml"],
                ["-v", '"$PWD/monitoring:/monitoring:ro"', "-v", '"$PWD/monitoring/data/loki:/loki"'],
                lab,
                "loki",
            ),
            _container(
                names["vector"],
                images.get("vector", "timberio/vector"),
                ["--config", "/monitoring/vector/vector.yaml"],
                [
                    "-v",
                    '"$PWD/monitoring:/monitoring:ro"',
                    "-v",
                    '"$PWD/monitoring/data/vector:/vector-data"',
                    "-v",
                    "/var/run/docker.sock:/var/run/docker.sock:ro",
                ],
                lab,
                "vector",
            ),
        ]
    if needs(plan, "gnmi"):
        lines.append(
            _container(
                names["gnmic"],
                images.get("gnmic", "ghcr.io/openconfig/gnmic"),
                ["subscribe", "--config", "/monitoring/gnmic/gnmic.yml"],
                ["-v", '"$PWD/monitoring:/monitoring:ro"'],
                lab,
                "gnmic",
            )
        )
    if needs(plan, "snmp"):
        snmp_port = ep.snmp.rsplit(":", 1)[1]
        lines.append(
            _container(
                names["snmp"],
                images.get("snmp", "prom/snmp-exporter"),
                [f"--web.listen-address=127.0.0.1:{snmp_port}"],
                [],
                lab,
                "snmp",
            )
        )
    if get(cfg, "grafana.enabled", True):
        env = [x for k, v in grafana_env(cfg, ep.grafana_port).items() for x in ("-e", f"{k}={v}")]
        lines.append(
            _container(
                names["grafana"],
                images.get("grafana", "grafana/grafana"),
                [],
                [
                    *env,
                    "-v",
                    '"$PWD/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro"',
                    "-v",
                    '"$PWD/monitoring/grafana/dashboards:/etc/netlab-dashboards:ro"',
                    "-v",
                    f'"$PWD/monitoring/dashboards:{USER_DASHBOARDS_MOUNT}:ro"',
                    "-v",
                    '"$PWD/monitoring/data/grafana:/var/lib/grafana"',
                ],
                lab,
                "grafana",
            )
        )
    down = [
        "#!/bin/bash",
        "# Generated by the netlab monitoring plugin: stop the monitoring stack (metrics stay in monitoring/data)",
        f"docker rm -f {' '.join(names.values())} >/dev/null 2>&1 || true",
    ]
    return {"up.sh": "\n".join(lines) + "\n", "down.sh": "\n".join(down) + "\n"}


# ------------------------------------------------------------------ node placement


def component_nodes(cfg: dict, needs_gnmi: bool, needs_snmp: bool) -> dict[str, dict]:
    """Monitoring containers as netlab nodes (placement: node). Paths are relative to the lab."""
    images = cfg.get("images") or {}
    ports = {**DEFAULT_PORTS, **(cfg.get("ports") or {})}
    prefix = cfg.get("node_prefix") or "mon"
    am = f"{prefix}-alertmanager:{ports['alertmanager']}" if notify.enabled(cfg) else None
    nodes: dict[str, dict] = {
        f"{prefix}-collector": {
            "image": images.get("collector", "python:3.13-alpine"),
            "cmd": f"python3 -m nlmon --plan /monitoring/plan.json --listen :{ports['collector']}",
            "env": {"PYTHONPATH": "/monitoring/collector"},
            "binds": [
                "monitoring:/monitoring:ro",
                "/proc:/host/proc:ro",
                "/sys:/host/sys:ro",
                "/var/run/docker.sock:/var/run/docker.sock:ro",
            ],
        },
        f"{prefix}-tsdb": {
            "image": images.get("tsdb", "victoriametrics/victoria-metrics"),
            "cmd": " ".join(tsdb_args(cfg, ports["tsdb"], "/monitoring/tsdb/scrape.yml", "/storage")),
            "binds": ["monitoring:/monitoring:ro", "monitoring/data/tsdb:/storage"],
            "ports": [f"{ports['tsdb']}:{ports['tsdb']}"],
        },
        f"{prefix}-vmalert": {
            "image": images.get("vmalert", "victoriametrics/vmalert"),
            "cmd": " ".join(vmalert_args(f"{prefix}-tsdb:{ports['tsdb']}", f":{ports['vmalert']}", am)),
            "binds": ["monitoring:/monitoring:ro"],
            "ports": [f"{ports['vmalert']}:{ports['vmalert']}"],
        },
    }
    if am:
        nodes[f"{prefix}-alertmanager"] = {
            "image": images.get("alertmanager", "prom/alertmanager"),
            "cmd": " ".join(alertmanager_args(f":{ports['alertmanager']}")),
            "binds": ["monitoring:/monitoring:ro"],
        }
    if logs.enabled(cfg):
        nodes[f"{prefix}-loki"] = {
            "image": images.get("loki", "grafana/loki"),
            "cmd": "-config.file=/monitoring/loki/loki.yml",
            "binds": ["monitoring:/monitoring:ro", "monitoring/data/loki:/loki"],
        }
        nodes[f"{prefix}-vector"] = {
            "image": images.get("vector", "timberio/vector"),
            "cmd": "--config /monitoring/vector/vector.yaml",
            "binds": [
                "monitoring:/monitoring:ro",
                "monitoring/data/vector:/vector-data",
                "/var/run/docker.sock:/var/run/docker.sock:ro",
            ],
            "ports": [f"{ports['syslog']}:{ports['syslog']}/udp"],
        }
    if needs_gnmi:
        nodes[f"{prefix}-gnmic"] = {
            "image": images.get("gnmic", "ghcr.io/openconfig/gnmic"),
            "cmd": "subscribe --config /monitoring/gnmic/gnmic.yml",
            "binds": ["monitoring:/monitoring:ro"],
        }
    if needs_snmp:
        nodes[f"{prefix}-snmp"] = {
            "image": images.get("snmp", "prom/snmp-exporter"),
            "cmd": f"--web.listen-address=:{ports['snmp']}",
        }
    if get(cfg, "grafana.enabled", True):
        nodes[f"{prefix}-grafana"] = {
            "image": images.get("grafana", "grafana/grafana"),
            "env": grafana_env(cfg, ports["grafana"]),
            "binds": [
                "monitoring/grafana/provisioning:/etc/grafana/provisioning:ro",
                "monitoring/grafana/dashboards:/etc/netlab-dashboards:ro",
                f"monitoring/dashboards:{USER_DASHBOARDS_MOUNT}:ro",
                "monitoring/data/grafana:/var/lib/grafana",
            ],
            "ports": [f"{ports['grafana']}:{ports['grafana']}"],
        }
    return nodes
