"""Shared response models for the netlab APP API.

These are the single source of truth for response shapes. They are attached to
every endpoint via ``response_model=`` so FastAPI's generated OpenAPI schema is
complete, and the frontend's TypeScript types are generated from that schema
(``frontend/src/api/generated.ts`` via ``npm run gen:api``) — no hand-rolled
duplication, no drift between Python and TS.

Genuinely dynamic payloads (the clab-ui topology snapshot, the netlab source
model, ``netlab inspect`` output) stay typed as open objects on purpose: fully
modelling netlab's topology dict here would be large and brittle, and the canvas
already validates them on the clab-ui side.

Split by domain across this package's modules (core, lab, topology, lenses,
readiness, reports, teaching, plugins, docs); re-exported here so existing
``from app.contract.responses import X`` call sites are unaffected.
"""

from __future__ import annotations

from app.contract.responses.core import (
    CommandResult,
    ConfigPreviewFile,
    ConfigPreviewResult,
    DeployDiffResult,
    HealthStatus,
    NetlabComponentStatus,
    NetlabEnvironment,
    OkMessageResult,
    OkResult,
    RevisionResult,
    RuntimeContainer,
    RuntimeInterface,
    RuntimeInterfaceStats,
    SetNetlabPathRequest,
    ValidationIssue,
    ValidationResult,
    VersionResult,
)
from app.contract.responses.deployment import (
    DeploymentEvent,
    DeploymentLog,
    DeploymentLogLine,
    DeploymentNodeDetail,
    DeploymentOverview,
    DeploymentRecap,
    DeploymentSummary,
)
from app.contract.responses.docs import DeviceEntry, DocsDocument
from app.contract.responses.lab import (
    DockerImage,
    ExampleLab,
    ExampleLabListResult,
    FileDocument,
    FileTreeEntry,
    FileTreeResult,
    FsBrowseResult,
    FsEntry,
    IconInfo,
    IconListResult,
    ImageOpResult,
    KindImageReference,
    LabFileEntry,
    LabInstance,
    LabInstanceAction,
    TopologyRef,
    WorkspaceEntry,
    WorkspaceListResult,
)
from app.contract.responses.lenses import (
    AddressingLens,
    ControlPlaneLens,
    DerivationField,
    DerivationLens,
    DerivationNode,
    LensAddressAssignment,
    LensAddressPool,
    LensBundleResult,
    LensEndpoint,
    LensLoopback,
    LensNodeDomain,
    LensSegment,
    LensServiceNode,
    LensWarning,
    PathHop,
    PathResult,
    ProtocolAdjacency,
    ProtocolMarker,
    ReachabilityLens,
    ServiceEvpnSummary,
    ServiceExplorerLens,
    ServiceTunnel,
    ServiceVlan,
    ServiceVlanEdge,
    ServiceVlanEvpn,
    ServiceVrf,
    ServiceVtep,
    ValidationLens,
    ValidationSummary,
    ValidationTest,
)
from app.contract.responses.plugins import (
    Plugin,
    PluginDebug,
    PluginImportRequest,
    PluginImportResult,
    PluginPipeline,
    PluginPipelineEntry,
    PluginTemplate,
)
from app.contract.responses.readiness import (
    ConfigDiffFile,
    ConfigDiffResult,
    ConfigDiffSummary,
    ReadinessCheck,
    ReadinessResult,
    ReadinessSummary,
)
from app.contract.responses.reports import (
    ReportCatalogResult,
    ReportDescriptor,
    ReportRunRequest,
    ReportRunResult,
    ReportTable,
)
from app.contract.responses.teaching import (
    TeachingDocument,
    TeachingSaveRequest,
    TeachingSaveResult,
    TeachingStep,
    TourView,
)
from app.contract.responses.topology import (
    CommandAck,
    CreateSessionResult,
    CustomNodesResult,
    GroupInfo,
    GroupsResult,
    InstantiateResult,
    MultiserverResult,
    MultiserverVxlan,
    NetlabLinkResult,
    SnapshotResponse,
    TemplatesResult,
    UnitExportBundle,
    UnitImportRequest,
    UnitImportResult,
    UnitInstance,
    UnitInstancesResult,
    WorkerInfo,
)

__all__ = [
    "AddressingLens",
    "CommandAck",
    "CommandResult",
    "ConfigDiffFile",
    "ConfigDiffResult",
    "ConfigDiffSummary",
    "ConfigPreviewFile",
    "ConfigPreviewResult",
    "ControlPlaneLens",
    "CreateSessionResult",
    "CustomNodesResult",
    "DeployDiffResult",
    "DeploymentEvent",
    "DeploymentLog",
    "DeploymentLogLine",
    "DeploymentNodeDetail",
    "DeploymentOverview",
    "DeploymentRecap",
    "DeploymentSummary",
    "DerivationField",
    "DerivationLens",
    "DerivationNode",
    "DeviceEntry",
    "DockerImage",
    "DocsDocument",
    "ExampleLab",
    "ExampleLabListResult",
    "FileDocument",
    "FileTreeEntry",
    "FileTreeResult",
    "FsBrowseResult",
    "FsEntry",
    "GroupInfo",
    "GroupsResult",
    "HealthStatus",
    "IconInfo",
    "IconListResult",
    "ImageOpResult",
    "InstantiateResult",
    "KindImageReference",
    "LabFileEntry",
    "LabInstance",
    "LabInstanceAction",
    "LensAddressAssignment",
    "LensAddressPool",
    "LensBundleResult",
    "LensEndpoint",
    "LensLoopback",
    "LensNodeDomain",
    "LensSegment",
    "LensServiceNode",
    "LensWarning",
    "MultiserverResult",
    "MultiserverVxlan",
    "NetlabComponentStatus",
    "NetlabEnvironment",
    "NetlabLinkResult",
    "OkMessageResult",
    "OkResult",
    "PathHop",
    "PathResult",
    "Plugin",
    "PluginDebug",
    "PluginImportRequest",
    "PluginImportResult",
    "PluginPipeline",
    "PluginPipelineEntry",
    "PluginTemplate",
    "ProtocolAdjacency",
    "ProtocolMarker",
    "ReachabilityLens",
    "ReadinessCheck",
    "ReadinessResult",
    "ReadinessSummary",
    "ReportCatalogResult",
    "ReportDescriptor",
    "ReportRunRequest",
    "ReportRunResult",
    "ReportTable",
    "RevisionResult",
    "RuntimeContainer",
    "RuntimeInterface",
    "RuntimeInterfaceStats",
    "ServiceEvpnSummary",
    "ServiceExplorerLens",
    "ServiceTunnel",
    "ServiceVlan",
    "ServiceVlanEdge",
    "ServiceVlanEvpn",
    "ServiceVrf",
    "ServiceVtep",
    "SetNetlabPathRequest",
    "SnapshotResponse",
    "TeachingDocument",
    "TeachingSaveRequest",
    "TeachingSaveResult",
    "TeachingStep",
    "TemplatesResult",
    "TopologyRef",
    "TourView",
    "UnitExportBundle",
    "UnitImportRequest",
    "UnitImportResult",
    "UnitInstance",
    "UnitInstancesResult",
    "ValidationIssue",
    "ValidationLens",
    "ValidationResult",
    "ValidationSummary",
    "ValidationTest",
    "VersionResult",
    "WorkerInfo",
    "WorkspaceEntry",
    "WorkspaceListResult",
]
