"""Read the per-node configuration artifacts generated by ``netlab create``."""

from __future__ import annotations

from pathlib import Path

MAX_FILE_BYTES = 512 * 1024


def read_node_files(topology_path: str | Path, node: str) -> list[dict[str, str]]:
    """Return textual files below ``node_files/<node>`` in stable path order."""
    root = Path(topology_path).parent / "node_files" / node
    if not root.is_dir():
        return []

    files: list[dict[str, str]] = []
    for candidate in sorted(path for path in root.rglob("*") if path.is_file()):
        try:
            if candidate.stat().st_size > MAX_FILE_BYTES:
                continue
            raw = candidate.read_bytes()
            if b"\0" in raw:
                continue
            content = raw.decode("utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        files.append({"path": candidate.relative_to(root).as_posix(), "content": content})
    return files
